pluginManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    versionCatalogs {
        libs {
            from(files("./libs.versions.toml"))
        }
    }
}

rootProject.name = "TTS Server"
include ':app'
include ':lib-gojni'
include ':lib-gojni-aar'
//include ':lib-tts'
//include ':lib-script-engine'
//include ':lib-common'
//include ':core'
include ':lib-script-engine'
include ':lib-common'
include ':lib-compose'
